config/routes.rb
Rails.application.routes.draw do
  resources :albums
  get 'welcome/index'
  

  root 'welcome#index'
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:album_name, :artist, :release_date, :stars, :listened_date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :album_name %>
    <%= form.text_field :album_name %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.text_field :release_date, data: { behavior: "flatpickr" }, placeholder: "Select date." %>
  </div>

  <div class="field">
    <%= form.label :stars %>
    <%= form.text_field :stars, placeholder: "An integer 0-10" %>
  </div>

  <div class="field">
    <%= form.label :listened_date %>
    <%= form.text_field :listened_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>Album name</th>
      <th>Artist</th>
      <th>Release date</th>
      <th>Stars</th>
      <th>Listened date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.album_name %></td>
        <td><%= album.artist %></td>
        <td><%= album.release_date %></td>
        <td><%= album.stars %></td>
        <td><%= album.listened_date %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<div class="has-text-black is-size-4">Add a new album here.</div>

<hr>

<nav class="level">
<%= render 'form', album: @album %>


<%#<%= link_to('Add to DB', @album.form.submit, :class => "button is-light is-filled") %>
<%= link_to('Back', albums_path, :class => "button is-light is-filled") %>
</nav>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album name:</strong>
  <%= @album.album_name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @album.release_date %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @album.stars %>
</p>

<p>
  <strong>Listened date:</strong>
  <%= @album.listened_date %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Lou's music suggestions</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <header class="header">
        <div class="container">
            <nav class="level">
                <div class="level-left">
                    <div class="level-item">
                      <div class="has-text-white is-size-3">Lou's good-ass album suggestions</div>
                    </div>
                </div>
                <div class="level-right">
                    <p class="level-item">
                        <%= link_to("Home", root_path, :class => "button is-dark is-filled") %>
                    </p>                        
                    <p class="level-item">                        
                        <%= link_to("Album list", albums_path, :class => "button is-dark is-filled") %>
                    </p>
                    <p class="level-item">                        
                        <%= link_to("About", albums_path, :class => "button is-dark is-filled") %>
                    </p>                    
                </div>
            </nav>
        </div>
    </header>
</head>

<body>
    <section class="section">
        <div class="container">
            <%= yield %>
        </div>
    </section>
</body>

<footer class="footer">
    <div class="container">
        Copyright © 2020 Lou Bernardi. All rights reserved.
    </div>
</footer>

</html>

app/views/welcome/index.html.erb
<h1>Random album:</h1>